# Generated by Django 4.2.7 on 2023-12-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comment_article_article_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comment',
            new_name='comments',
        ),
    ]
